name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
        #     channel: stable
      # - name: Resolve Flutter dependency
      #   run: flutter pub get
      # - name: Analyze and build
      #   run: flutter analyze && flutter build apk --release
      - name: Build
        run: |
          mkdir -p build/app/outputs/apk/release
          touch build/app/outputs/apk/release/app-release.apk
          echo "Build successfully."
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: build/app/outputs/apk/release/app-release.apk
  release:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: apk-artifact/app-release.apk