name: ci
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
  push:
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Resolve Flutter dependency
        run: flutter pub get
      - name: Run flutter analyse
        run: flutter analyze
      - name: Run flutter test
        run: flutter test
  build:
    if: ${{ github.ref_type == 'tag' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Resolve Flutter dependency
        run: flutter pub get
      - name: Build release apk
        run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: build/app/outputs/apk/release/app-release.apk
  release:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: apk-artifact/app-release.apk